/* 2026-09-10: ERP common controls, visual refinement and confirmed store-item exclusion. */
const searchIcon='<svg class="icon" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="8.7" cy="8.7" r="5.8" stroke="currentColor" stroke-width="1.6"/><path d="m13 13 4.2 4.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>';
const exportIcon='<svg class="icon" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M11 2.5H4v15h11v-5M11 2.5l4 4h-4zM9 10h8m-3-3 3 3-3 3" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const storeDirectory=()=>tasks.filter((t,i,a)=>a.findIndex(x=>x.code===t.code)===i).map(t=>({code:t.code,name:t.store,org:t.org}));
let pickerDraft=new Set(),pickerSearch='',pickerOrg='全部',pageSize=10;

function storeTrigger(){const stores=storeDirectory().filter(s=>filters.stores.includes(s.code));const value=stores.map(s=>s.name).join('、');return `<div class="store-picker-trigger"><input aria-label="补货门店" readonly placeholder="" value="${esc(value)}" title="${esc(value)}" onclick="chooseStores()">${stores.length?'<button class="clear-selection" title="清空门店" aria-label="清空门店" onclick="filters.stores=[];render()">×</button>':''}<button title="选择补货门店" aria-label="选择补货门店" onclick="chooseStores()">${searchIcon}</button></div>`}
filterUI=function(){return `<div class="filter"><label>日期选择：<span class="date-pair"><input aria-label="开始日期" type="date" id="start" value="${filters.start}"><span>至</span><input aria-label="结束日期" type="date" id="end" value="${filters.end}"></span></label><label>组织：<select id="org">${['全部','示例一区','示例二区'].map(s=>`<option ${s===filters.org?'selected':''}>${s}</option>`).join('')}</select></label><label>补货门店：${storeTrigger()}</label><label class="field-check"><input id="activeOnly" type="checkbox" ${filters.active?'checked':''}>仅显示效期内任务${tip('按当前时点判断，补货阶段或跟进阶段任意一段处于生效期内，即纳入该任务；已完成但尚未到期的任务也纳入。')}</label><div class="filter-actions"><button class="primary" onclick="query()">${searchIcon}查询</button><button onclick="filters={org:'全部',stores:[],start:'2026-08-01',end:'2026-09-30',active:false};rfilter={};pages={};render()">重置</button></div></div>`};
query=function(){const start=document.querySelector('#start').value,end=document.querySelector('#end').value;if(!start||!end||start>end){toast('请选择有效日期范围，开始日期不能晚于结束日期');return}filters={...filters,org:document.querySelector('#org').value,start,end,active:document.querySelector('#activeOnly')?.checked||false};if(page==='records'){rfilter={task:document.querySelector('#rt').value.trim(),follow:document.querySelector('#rf').value.trim(),status:document.querySelector('#rs').value,fs:document.querySelector('#rfs').value}}pages={};render()};
readRecordFilters=query;

chooseStores=function(){pickerDraft=new Set(filters.stores);pickerSearch='';pickerOrg=document.querySelector('#org')?.value||filters.org;const d=document.querySelector('#modal');d.className='picker-dialog';d.innerHTML=`<div class="picker-head"><h2>选择门店</h2><button aria-label="关闭门店选择" onclick="closeModal()">×</button></div><div class="picker-body"><div class="picker-search"><span>门店代码/名称：</span><input id="pickerQuery" placeholder="请输入门店代码或名称" onkeydown="if(event.key==='Enter')searchStores()"><button onclick="searchStores()">${searchIcon}查询</button></div><div class="hint" style="margin-bottom:12px">查询范围：${esc(pickerOrg==='全部'?'当前权限范围':pickerOrg)}</div><div id="pickerTable"></div><div class="picker-selected" id="pickerCount"></div></div><div class="actions"><button onclick="closeModal()">取消</button><button class="primary" onclick="commitStores()">确定</button></div>`;drawStorePicker();d.showModal()};
function visibleStores(){return storeDirectory().filter(s=>(pickerOrg==='全部'||pickerOrg===s.org)&&(!pickerSearch||(s.code+' '+s.name).includes(pickerSearch)))}
function searchStores(){pickerSearch=document.querySelector('#pickerQuery').value.trim();drawStorePicker()}
function drawStorePicker(){const list=visibleStores();document.querySelector('#pickerTable').innerHTML=`<div class="tablewrap"><table><thead><tr><th style="width:42px"><input aria-label="全选查询到的门店" type="checkbox" ${list.length&&list.every(s=>pickerDraft.has(s.code))?'checked':''} onchange="toggleAllStores(this.checked)"></th><th>门店代码</th><th>门店名称</th><th>所属组织</th></tr></thead><tbody>${list.map(s=>`<tr><td><input aria-label="选择${s.name}" type="checkbox" ${pickerDraft.has(s.code)?'checked':''} onchange="this.checked?pickerDraft.add('${s.code}'):pickerDraft.delete('${s.code}');drawStorePicker()"></td><td>${s.code}</td><td>${s.name}</td><td>${s.org}</td></tr>`).join('')||'<tr><td colspan="4" class="picker-empty">没有符合查询条件的门店</td></tr>'}</tbody></table></div>`;document.querySelector('#pickerCount').textContent=`已选择 ${pickerDraft.size} 家门店　　共 ${list.length} 条`}
function toggleAllStores(checked){visibleStores().forEach(s=>checked?pickerDraft.add(s.code):pickerDraft.delete(s.code));drawStorePicker()}
function commitStores(){filters.stores=[...pickerDraft];const org=document.querySelector('#org'),start=document.querySelector('#start'),end=document.querySelector('#end');if(org&&start&&end)filters={...filters,org:org.value,start:start.value,end:end.value,active:document.querySelector('#activeOnly')?.checked||false};closeModal();pages={};render()}
const inheritedModal=modal;modal=function(...args){document.querySelector('#modal').className='';inheritedModal(...args)};

table=function(id,headers,data,raw=false){const size=pageSize,max=Math.max(1,Math.ceil(data.length/size)),current=Math.min(pages[id]||1,max);pages[id]=current;return `<div class="tablewrap" tabindex="0" aria-label="${id}明细表，可横向滚动"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${data.slice((current-1)*size,current*size).map(row=>`<tr>${row.map(c=>`<td>${raw?c:esc(c)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}"><div class="picker-empty">没有符合查询条件的数据<br><small>请修改条件后重新查询</small></div></td></tr>`}</tbody></table></div><div class="footer">共 ${data.length} 条 <button ${current===1?'disabled':''} onclick="pages['${id}']--;refreshTable('${id}')">上一页</button><span>${current} / ${max}</span><button ${current===max?'disabled':''} onclick="pages['${id}']++;refreshTable('${id}')">下一页</button><select aria-label="每页条数" onchange="pageSize=Number(this.value);pages={};refreshTable('${id}')">${[10,20,50,200].map(n=>`<option value="${n}" ${size===n?'selected':''}>${n} 条/页</option>`).join('')}</select></div>`};
function refreshTable(id){if(id==='generation'){closeModal();previewGeneration()}else render()}

// Membership is evaluated at the task level, not by whether one product has been handled.
function unfinishedTaskFor(storeCode,itemCode){return rows.find(r=>{if(r.code!==storeCode||r.g[0]!==itemCode)return false;const t=taskOf(r);return t.phase==='store'||(Boolean(r.f)&&Boolean(t.fid)&&t.phase!=='closed')})}
function generationCandidates(){return storeDirectory().flatMap(s=>goods.map(g=>{const existing=unfinishedTaskFor(s.code,g[0]);const blockedByBlack=rows.some(r=>r.code===s.code&&r.g[0]===g[0]&&r.black&&!r.blackRemoved&&(!r.date||r.date>='2026-09-09'));return{s,g,existing,allowed:!existing&&!blockedByBlack,reason:existing?(taskOf(existing).phase==='store'?'存在未结束的补货任务':'存在未结束的跟进任务'):blockedByBlack?'命中有效黑名单':'允许生成'}}))}
function previewGeneration(){const a=generationCandidates();modal('新补货任务生成校验',`<div class="picker-body"><div class="note">按门店＋商品过滤未结束的补货任务或跟进任务。即使该商品已处理，只要所属任务尚未结束，仍过滤。不同门店互不影响。</div>${table('generation',['门店','商品','生成结果','原因'],a.map(x=>[x.s.name,x.g[1],x.allowed?'可生成':'已过滤',x.reason]))}<p class="hint">演示候选 ${a.length} 条；过滤 ${a.filter(x=>!x.allowed).length} 条；可生成 ${a.filter(x=>x.allowed).length} 条。</p></div>`,a.some(x=>x.allowed)?'<button class="primary" onclick="generateNewTasks()">生成通过校验的任务</button>':'');document.querySelector('#modal').style.width='860px'}
function generateNewTasks(){const allowed=generationCandidates().filter(x=>x.allowed),created=[];for(const code of new Set(allowed.map(x=>x.s.code))){const group=allowed.filter(x=>x.s.code===code),s=group[0].s;const seq=tasks.filter(t=>t.code===code&&t.start.startsWith('2026-09-09')).length+1;const id=`20260909-${code}-${String(seq).padStart(3,'0')}`;const t={id,store:s.name,code,org:s.org,start:'2026-09-09 10:00',end:'2026-09-13 09:00',fs:'2026-09-13 09:30',fe:'2026-09-15 18:00',phase:'store',fid:'',person:'督导乙'};tasks.push(t);let next=Math.max(...rows.map(r=>r.id),0)+1;for(const x of group)rows.push({id:next++,task:id,g:x.g,store:s.name,code,org:s.org,s:'待补货',f:'',black:false,date:'',reason:'',order:'',n:0});created.push(id)}closeModal();render();toast(created.length?`已生成 ${created.length} 个演示任务，共 ${allowed.length} 个商品`:'没有可生成的商品，不创建空任务')}

function productArt(code){const color={P001:'#7ca8e9',P002:'#80b8c5',P003:'#bf9974',P004:'#e2bb87',P005:'#a9bf69',P006:'#b3abcf'}[code]||'#9fb1c8';const bottle=['P001','P002','P005'].includes(code);return `<svg viewBox="0 0 48 66" fill="none" aria-hidden="true">${bottle?`<rect x="18" y="3" width="12" height="7" rx="2" fill="${color}"/><path d="M18 10v7L12 26v31q0 5 5 5h14q5 0 5-5V26l-6-9v-7" fill="${color}" fill-opacity=".18" stroke="${color}"/><rect x="12" y="30" width="24" height="18" rx="2" fill="${color}"/><path d="M17 17v8M16 53v5" stroke="white" stroke-width="2"/><path d="M18 37h12M20 41h8" stroke="white" stroke-width="1.4"/>`:`<rect x="7" y="12" width="34" height="48" rx="3" fill="${color}"/><path d="M7 18h34M7 54h34" stroke="white" stroke-opacity=".5"/><rect x="12" y="25" width="24" height="22" rx="2" fill="white" fill-opacity=".8"/><circle cx="24" cy="36" r="6" fill="${color}"/><path d="M12 7h24" stroke="${color}" stroke-width="2"/>`}</svg>`}
const beforeRefineRender=render;
render=function(){beforeRefineRender();document.body.dataset.page=page;const app=document.querySelector('#app');
 document.querySelectorAll('.filter').forEach(f=>{if(f.querySelector('#start')){f.parentElement.classList.add('filter-panel')}});
 document.querySelectorAll('.panel').forEach(p=>{const heading=p.querySelector(':scope > div > h2');if(heading){heading.parentElement.classList.add('section-heading')}});
 document.querySelectorAll('button').forEach(b=>{const t=b.textContent.trim();if(t==='导出'){b.classList.add('export-btn');b.innerHTML=exportIcon+'导出'}if(t==='取消')b.style.background='white'});
 if(page==='records'){app.querySelectorAll('.filter-actions button').forEach(b=>{if(b.textContent.includes('查询'))b.remove()})}
 if(page==='dashboard'){const ann=app.querySelector('.annotation');if(ann)ann.textContent='日期放第一位；门店字段复用订单搜索选择器；保留原报表分组和字段顺序。'}
 if(page==='pool'||page==='push'){const p=app.querySelector('.panel');if(p)p.insertAdjacentHTML('beforeend',`<div class="note" style="margin-top:18px;margin-bottom:0"><b>未结束任务过滤</b><p style="margin:5px 0 10px">生成新补货任务前，按门店＋商品过滤仍在补货任务或跟进任务中的商品。</p><button onclick="previewGeneration()">演示生成校验</button></div>`)}
 if(page==='flow'){const p=app.querySelector('.panel');if(p)p.insertAdjacentHTML('beforeend','<p class="note">生成入口新增店品过滤：存在未结束补货任务或跟进任务时，本次不再为相同门店＋商品生成新推荐；其他店品继续处理。</p>')}
 if(page==='store'&&!order){const all=taskRows(tasks[0]).filter(r=>r.s==='待补货');document.querySelectorAll('.phone .product').forEach((el,i)=>{el.hidden=category!=='全部'&&all[i]?.g[4]!==category;const pic=el.querySelector('.pic');if(pic&&all[i])pic.innerHTML=productArt(all[i].g[0])});const btn=app.querySelector('.cats button');if(btn)btn.onclick=()=>filterStore('全部')}
 else {document.querySelectorAll('.phone .product').forEach((el,i)=>{const list=page==='follow'?followRows(tasks.find(t=>t.fid===followId)||tasks[1]):order?rows.filter(r=>order.rows.includes(r.id)):[];const pic=el.querySelector('.pic');if(pic&&list[i])pic.innerHTML=productArt(list[i].g[0])})}
 document.querySelectorAll('.tip').forEach(el=>{el.onmouseenter=()=>showTip(el);el.onfocus=()=>showTip(el);el.onmouseleave=hideTip;el.onblur=hideTip});
};
function showTip(el){hideTip();const bubble=document.createElement('div');bubble.id='floating-tip';bubble.setAttribute('role','tooltip');bubble.textContent=el.dataset.tip;document.body.append(bubble);const r=el.getBoundingClientRect();bubble.style.left=Math.max(8,Math.min(innerWidth-304,r.right-290))+'px';bubble.style.top=Math.min(innerHeight-bubble.offsetHeight-8,r.bottom+8)+'px'}
function hideTip(){document.querySelector('#floating-tip')?.remove()}
document.querySelector('#modal').addEventListener('close',()=>{document.querySelector('#modal').style.width='';hideTip()});
render();
