/* 2026-09-16 业务接龙：有效补货优先、多依据、回退、查询与黑名单。 */
const followMark=r=>!r.f?'—':r.f==='已补货'?'已跟进':r.f==='待跟进'?'待跟进':r.f==='已超时'?(['待补货','已拒绝'].includes(r.beforeTimeout)?'已跟进':'待跟进'):'已跟进';
const shippingName=r=>r.shippingStore||'示例配送中心';
function matchingEvidence(r,t,docs){return docs.filter(d=>['门店订单-仓配','调出单'].includes(d.type)&&['制单','审核'].includes(d.status)&&(d.type==='调出单'?d.receivingStore:d.store)===r.code&&d.product===r.g[0]&&d.quantity>0&&d.time>=t.fs&&d.time<t.fe)}
function relatedDocuments(r){if(Array.isArray(r.evidence))return r.evidence;return r.order?[{id:r.order,type:r.orderType||'门店订单-仓配',status:recordOrderState(r),quantity:r.n,time:taskOf(r).start}]:[]}
function relatedText(r){return relatedDocuments(r).map(d=>`${d.type} ${d.id}（${d.status}）`).join('；')||'—'}
function showRelated(id){const r=rows.find(r=>r.id===id),ds=relatedDocuments(r);modal('关联单据',`<p>${esc(r.store)} · ${esc(r.g[1])}</p>${table('related',['单据类型','单据编号','状态','本品数量'],ds.map(d=>[d.type,d.id,d.status,d.quantity]))}<p class="hint">展示该店品匹配的全部有效单据。订单与下游调出单不直接相加为补货数量；任务结束保留结束时关联快照。</p>`,'')}
function relatedLinks(r){const ds=relatedDocuments(r);return ds.length?`<button class="link-button" onclick="showRelated(${r.id})">${ds.length}张 · ${ds.map(d=>esc(d.id)).join('<br>')}</button>`:'—'}
applyFollowEvidence=function(t,documents){
  if(!t||t.phase!=='follow')return 0;
  let changed=0;
  for(const r of followRows(t)){
    const matches=matchingEvidence(r,t,documents),unique=[...new Map(matches.map(d=>[d.type+'|'+d.id,d])).values()];
    if(unique.length){
      if(r.f!=='已补货'){r.followActionBeforePurchase=r.f;changed++}
      r.evidence=unique.map(d=>({...d}));r.f='已补货';r.followed=true;
      // 延续既有数量字段，不对订单与其下游调出单叠加数量。
      const basis=unique.find(d=>d.type==='门店订单-仓配')||unique[0];
      r.order=basis.id;r.orderState=basis.status;r.orderType=basis.type;r.n=basis.quantity;
    }else if(r.f==='已补货'&&r.followActionBeforePurchase){
      r.f=r.followActionBeforePurchase;r.followed=r.f!=='待跟进';r.evidence=[];r.order='';r.orderState='';r.n=0;changed++;
    }
  }
  return changed;
};
function allEvidence(t){return followRows(t).flatMap(r=>relatedDocuments(r).map(d=>({...d,store:r.code,receivingStore:r.code,product:r.g[0],time:d.time||t.fs})))}
simulateFollowEvidence=function(type,status){const t=tasks.find(t=>t.fid===followId);if(!t||t.phase!=='follow'){toast('任务已结束，结果冻结');return}if(!type){toast('没有新增单据，现有处理标记不变');return}const a=followRows(t),r=a.find(r=>r.f==='已拒绝')||a.find(r=>['待跟进','待补货'].includes(r.f))||a[0];if(!r)return;const docs=allEvidence(t);docs.push({id:(type==='调出单'?'DC':'DD')+'-DEMO-'+r.id+'-'+(docs.length+1),type,status,store:r.code,receivingStore:r.code,product:r.g[0],quantity:1,time:t.fs});applyFollowEvidence(t,docs);render();toast('已识别有效补货：已跟进＋已补货')};
function simulateMultipleEvidence(){const t=tasks.find(t=>t.fid===followId);if(!t||t.phase!=='follow')return;const r=followRows(t).find(r=>r.f==='已拒绝')||followRows(t).find(r=>r.f!=='已补货')||followRows(t)[0];if(!r)return;const docs=allEvidence(t);for(const[type,status,suffix]of[['门店订单-仓配','制单','A'],['门店订单-仓配','审核','B'],['调出单','审核','C']])docs.push({id:'DEMO-'+r.id+'-'+suffix,type,status,store:r.code,receivingStore:r.code,product:r.g[0],quantity:1,time:t.fs});applyFollowEvidence(t,docs);render();toast('同一店品已关联3张有效单据')}
function simulateEvidenceVoid(all=false){const t=tasks.find(t=>t.fid===followId);if(!t||t.phase!=='follow')return;const r=followRows(t).find(r=>r.followActionBeforePurchase&&r.f==='已补货');if(!r){toast('请先模拟补货，再演示单据失效');return}const ds=relatedDocuments(r),remove=all?ds.map(d=>d.id):[ds[0].id];applyFollowEvidence(t,allEvidence(t).filter(d=>!remove.includes(d.id)));render();toast(r.f==='已补货'?'仍有有效依据，保持已补货':'无有效依据，恢复为'+r.f)}
const closeFollow=endFollow;endFollow=function(){const t=tasks.find(t=>t.fid===followId);followRows(t).forEach(r=>r.beforeTimeout=r.f);closeFollow()};

const listChoices=(values,selected)=>['',...values].map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v||'全部')}</option>`).join('');
function recordResults(){return filterRows().filter(r=>(!rfilter.task||r.task.includes(rfilter.task))&&(!rfilter.follow||(r.f&&taskOf(r).fid.includes(rfilter.follow)))&&(!rfilter.status||r.s===rfilter.status)&&(!rfilter.fs||r.f===rfilter.fs)&&(!rfilter.shipping||((r.shippingCode||'DC001')+' '+shippingName(r)).includes(rfilter.shipping))&&(!rfilter.product||(r.g[0]+' '+r.g[1]).includes(rfilter.product))&&(!rfilter.document||relatedDocuments(r).some(d=>d.id.includes(rfilter.document)))&&(!rfilter.reason||(r.reason||'无拒绝原因')===rfilter.reason)&&(!rfilter.black||(r.black?'是':'否')===rfilter.black))}
queryRecords=function(){const value=id=>document.querySelector(id).value.trim();const start=value('#start'),end=value('#end');if(!start||!end||start>end){toast('请选择有效日期范围');return}filters={...filters,start,end,org:value('#org'),active:document.querySelector('#activeOnly').checked};rfilter={task:value('#rt'),follow:value('#rf'),status:value('#rs'),fs:value('#rfs'),reason:value('#rr'),black:value('#rb'),shipping:value('#rshipping'),product:value('#rproduct'),document:value('#rdocument')};pages={};render()};
readRecordFilters=queryRecords;
records=function(){const a=recordResults(),reasons=[...new Set(rows.map(r=>r.reason).filter(Boolean))];const headers=['补货任务编码','推送时间','补货结束时间','跟进任务编码','跟进开始时间','跟进结束时间','发货门店','补货门店','商品代码','商品名称','补货状态','跟进人','跟进状态','补货数量','关联单据','关联单据状态','拒绝原因','是否黑名单','截止日期'];const data=a.map(r=>{const t=taskOf(r);return[r.task,t.start,t.end,r.f?t.fid:'—',r.f?t.fs:'—',r.f?t.fe:'—',shippingName(r),r.store,r.g[0],r.g[1],r.s,r.f?t.person:'—',r.f?(followMark(r)===r.f?r.f:followMark(r)+' · '+r.f):'—',r.n,relatedText(r),relatedDocuments(r).map(d=>d.status).join('；')||'—',r.reason||'—',r.black?'是':'否',r.black?r.date||'永久':'—']});exports.records=[headers,data];const show=data.map((line,i)=>line.map((v,j)=>j===14?relatedLinks(a[i]):[10,12].includes(j)?tag(v):esc(v)));return `<div class="panel"><div class="toolbar"><button onclick="queryRecords()">查询</button><button onclick="exportRows('records')">导出</button></div>${filterUI()}<div class="filter"><label>补货任务编码<input id="rt" value="${esc(rfilter.task||'')}" placeholder="包含式模糊搜索"></label><label>跟进任务编码<input id="rf" value="${esc(rfilter.follow||'')}" placeholder="包含式模糊搜索"></label><label>发货门店<input id="rshipping" value="${esc(rfilter.shipping||'')}" placeholder="门店代码/名称"></label><label>商品<input id="rproduct" value="${esc(rfilter.product||'')}" placeholder="商品代码/名称"></label><label>关联单据号<input id="rdocument" value="${esc(rfilter.document||'')}" placeholder="订单/调出单编号"></label><label>补货状态<select id="rs">${listChoices(['待补货','已补货','已删除','已超时'],rfilter.status)}</select></label><label>跟进状态<select id="rfs">${listChoices(['待跟进','待补货','已补货','已拒绝','已超时'],rfilter.fs)}</select></label><label>拒绝原因<select id="rr">${listChoices(['无拒绝原因',...reasons],rfilter.reason)}</select></label><label>是否黑名单<select id="rb">${listChoices(['是','否'],rfilter.black)}</select></label></div>${table('records',headers,show,true)}</div>`};

let followQuery={text:'',done:'',start:'',end:''};
function followTaskResults(){return tasks.filter(t=>t.fid&&(tabStage==='live'?t.phase==='follow':t.phase==='closed')&&(!followQuery.text||(t.fid+' '+t.store+' '+t.code).includes(followQuery.text))&&(!followQuery.done||(fComplete(t)?'已完成':'未完成')===followQuery.done)&&(!followQuery.start||t.fs.slice(0,10)>=followQuery.start)&&(!followQuery.end||t.fs.slice(0,10)<=followQuery.end))}
function queryFollow(){const value=id=>document.querySelector(id).value.trim();const q={text:value('#followSearch'),done:value('#followDone'),start:value('#followFrom'),end:value('#followTo')};if(q.start&&q.end&&q.start>q.end){toast('开始日期不能晚于结束日期');return}followQuery=q;render()}
const existingFollowPage=followPage;
followPage=function(){if(!followDetail){const ts=followTaskResults();return `<div class="mobile-wrap"><div class="phone"><div class="ptop">补货跟进</div><div class="cats"><button class="${tabStage==='live'?'sel':''}" onclick="tabStage='live';render()">生效中</button><button class="${tabStage==='past'?'sel':''}" onclick="tabStage='past';render()">已超期</button></div><div class="follow-filters"><input id="followSearch" aria-label="任务编号或门店" placeholder="任务编号/门店代码或名称" value="${esc(followQuery.text)}"><label>完成状态<select id="followDone">${listChoices(['已完成','未完成'],followQuery.done)}</select></label><label>跟进开始日期<input id="followFrom" type="date" aria-label="跟进开始日期起" value="${followQuery.start}">至<input id="followTo" type="date" aria-label="跟进开始日期止" value="${followQuery.end}"></label><button onclick="queryFollow()">查询</button><button onclick="followQuery={text:'',done:'',start:'',end:''};render()">重置</button></div>${ts.map(t=>`<div class="card" role="button" tabindex="0" onclick="followId='${t.fid}';followDetail=true;render()"><b>${t.fid}</b>${tag(fComplete(t)?'已完成':'未完成')}<p>${t.store} · ${t.person}</p><div>进度 ${fDone(t)} / ${followRows(t).length}</div><small>${t.fs} 至 ${t.fe}</small></div>`).join('')||'<p class="card">无匹配任务</p>'}</div><section><h2>督导任务列表</h2><p>按任务编号、门店、完成状态、跟进开始日期查询。</p><p>有效补货统一计入已跟进；不要求督导必须在线上操作过。</p></section></div>`}
 const t=tasks.find(t=>t.fid===followId),a=t?followRows(t):[];
 let html=existingFollowPage();
 for(const r of a){html=html.replace(`<p>${tag(r.f)}</p>`,`<p>${followMark(r)===r.f?tag(r.f):tag(followMark(r))+' '+tag(r.f)}</p>${relatedLinks(r)}`)}
 return html.replace('<div class="toolbar"><button','<div class="toolbar"><button '+(t?.phase!=='follow'?'disabled':'')+' onclick="simulateMultipleEvidence()">模拟多张有效单据</button><button '+(t?.phase!=='follow'?'disabled':'')+' onclick="simulateEvidenceVoid()">作废一张依据</button><button '+(t?.phase!=='follow'?'disabled':'')+' onclick="simulateEvidenceVoid(true)">作废全部依据</button><button').replace('有有效补货时自动转“已补货”，优先于“已拒绝”。','有有效补货时计为“已跟进＋已补货”，优先于“已拒绝”；全部有效依据失效时恢复补货前状态。');
};

let blackQuery={org:'',store:'',product:''},blackSelected=new Set();
function blacklistResults(){return rows.filter(r=>r.black&&!r.blackRemoved&&(!blackQuery.org||r.org===blackQuery.org)&&(!blackQuery.store||(r.code+' '+r.store).includes(blackQuery.store))&&(!blackQuery.product||(r.g[0]+' '+r.g[1]).includes(blackQuery.product)))}
function queryBlacklist(){blackQuery={org:document.querySelector('#blackOrg').value,store:document.querySelector('#blackStore').value.trim(),product:document.querySelector('#blackProduct').value.trim()};blackSelected.clear();render()}
function confirmBlackRemoval(ids){if(!ids.length)return;modal('删除黑名单记录',`确认删除选中的${ids.length}条记录？删除仅解除这些记录的屏蔽；同一门店＋商品仍有其他有效记录时，仍会屏蔽。需要完全解除时，请按门店、商品查询并选中全部相关有效记录。`,`<button class="primary" onclick='removeBlackRecords(${JSON.stringify(ids)})'>确认删除</button>`)}
function removeBlackRecords(ids){rows.filter(r=>ids.includes(r.id)&&r.black).forEach(r=>r.blackRemoved=true);blackSelected.clear();closeModal();render();toast('已删除选中记录，历史跟进结果不变')}
blacklistPage=function(){const a=blacklistResults(),hs=['组织','门店名称','门店代码','商品名称','商品代码','截止日期','来源跟进任务','操作人','操作时间'];const data=a.map(r=>[r.org,r.store,r.code,r.g[1],r.g[0],r.date||'永久',taskOf(r).fid,taskOf(r).person,taskOf(r).fs]);exports.blacklist=[hs,data];return `<div class="panel"><div class="filter"><label>组织<select id="blackOrg">${listChoices(['示例一区','示例二区'],blackQuery.org)}</select></label><label>门店<input id="blackStore" placeholder="门店代码/名称" value="${esc(blackQuery.store)}"></label><label>商品<input id="blackProduct" placeholder="商品代码/名称" value="${esc(blackQuery.product)}"></label><button onclick="queryBlacklist()">查询</button><button onclick="blackQuery={org:'',store:'',product:''};blackSelected.clear();render()">重置</button></div><div class="toolbar"><button onclick="exportRows('blacklist')">导出</button><button ${!blackSelected.size?'disabled':''} onclick="confirmBlackRemoval([...blackSelected])">删除选中</button></div><p class="hint">到期自动解除该条记录的屏蔽，之后满足推荐条件可再次推送和拉黑；列表保留不同批次的记录。</p>${table('blacklist',['<input type="checkbox" aria-label="全选查询结果" '+(a.length&&a.every(r=>blackSelected.has(r.id))?'checked':'')+' onchange="blackSelected=this.checked?new Set(blacklistResults().map(r=>r.id)):new Set();render()">',...hs,'操作'],data.map((line,i)=>[`<input type="checkbox" aria-label="选择黑名单${a[i].id}" ${blackSelected.has(a[i].id)?'checked':''} onchange="this.checked?blackSelected.add(${a[i].id}):blackSelected.delete(${a[i].id});render()">`,...line.map(esc),`<button onclick="confirmBlackRemoval([${a[i].id}])">删除</button>`]),true)}</div>`};
const previousReset=reset;reset=function(){previousReset();followQuery={text:'',done:'',start:'',end:''};blackQuery={org:'',store:'',product:''};blackSelected.clear();render()};
const previousFlow=flow;flow=function(){return previousFlow()+`<div class="panel"><h2>有效期内持续重判</h2><p>待跟进／待补货／已拒绝 → 有效补货 → 已跟进＋已补货。已完成任务仍继续监控；有一张有效依据即保留已补货，全部失效时恢复此前处理状态；到期冻结。</p><p>任务系统途中更换督导后，向新督导补推IM；我方接收最新负责人，不增加人工转派入口。</p></div>`};
render();
